### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by NPCRUS** [karllhughes/laravel-php-7#1]
I setuped your docker imahe on DigitalOcean, everything works fine, i used clean laravel default project . But when i trying to get response from ip adress i got this in browser
![default](https://cloud.githubusercontent.com/assets/13519208/13956843/4e489118-f05b-11e5-8c8f-c39a0224b8ce.PNG)

**Comment by karllhughes** [comment]
Hey @NPCRUS thanks for submitting an issue here. Have you tried running it locally? I haven't used this in production, but I'll try to replicate your issue this evening when I get home.

**Comment by NPCRUS** [comment]
@karllhughes , i didn't try to run it locally, thank you so much for answer.

**Comment by karllhughes** [comment]
@NPCRUS I tried this out on a digital ocean droplet as well, and had similar trouble. My fix was to change the permissions of my /storage directory to allow the docker user to modify them.

I'm going to update the readme to make sure this is clear. The permissions in Laravel apps can be problematic for serving through nginx/apache, so this will probably trip people up. Let me know if this works for you.

**Comment by NPCRUS** [comment]
@karllhughes hello man, i tried it out, it works fine thank you very much for support!!!
